### Create User
POST http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Basic admin password


  {
    "username": "admin",
    "password": "adminpassword",
    "email": "admin@example.com",
    "role": "ADMIN"
  }

###

### Create User
POST http://localhost:8080/api/v1/users
Content-Type: application/json
Authorization: Basic user password

{
  "username": "user",
  "password": "adminpassword",
  "email": "admin@example.com"
}

###

POST http://localhost:8080/api/v1/tickets
Content-Type: application/json
Authorization: Basic admin password

{
  "subject": "Issue 1",
  "description": "Details about Issue 1",
  "user": {
    "id": "1"
  }
}

###

POST http://localhost:8080/api/v1/tickets
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

{
  "subject": "Issue 2",
  "description": "Details about Issue 2",
  "user": {
    "id": "2"
  }
}

###

### Update User
PUT http://localhost:8080/api/v1/users/1
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

{
  "username": "updatedUser",
  "email": "updateduser@example.com",
  "role": "ADMIN"
}

###

### Get User by ID
GET http://localhost:8080/api/v1/users/1
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###

### Get All Users
GET http://localhost:8080/api/v1/users
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###

### Delete User
DELETE http://localhost:8080/api/v1/users/1

###

### Create Ticket
POST http://localhost:8080/api/v1/tickets
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==
###


### Get All Tickets
GET http://localhost:8080/api/v1/tickets
Accept: application/json
Authorization: Basic user password

###

### Get Ticket by ID
GET http://localhost:8080/api/v1/tickets/{ticketId}
Accept: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

###

### Update Ticket
PUT http://localhost:8080/api/v1/tickets/{ticketId}
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

{
  "subject": "Updated Issue Title",
  "description": "Updated details about the fix..."
}

###

### Close Ticket
PUT http://localhost:8080/api/v1/tickets/{ticketId}/close
Content-Type: application/json
Authorization: Basic dXNlcjpwYXNzd29yZA==

{
  "closingComment": "Fixed the issue"
}

###

### post a new comment
POST http://localhost:8080/api/v1/comments/1
Content-Type: application/json
Authorization: Basic user password

{
  "content": "Further information",
  "user": "2"
}
